name: Build MPV library (macOS - ARM64)

on:
  push:
    branches: [ "main", "x/oob/v1.0.x" ]
  pull_request:
    branches: [ "main", "x/oob/v1.0.x" ]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setting up environment
        run: |
          brew install meson ffmpeg libass luajit jpeg-turbo libplacebo
      - name: MPV compilation
        run: |
          cd assets/mpv ; meson setup build --prefix=$(pwd)/outlib ; meson compile -C build
      - name: Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "MPV library"
          path: assets/mpv/outlib
