name: Build MPV library (FreeBSD - AMD64)

on:
  push:
    branches: [ "main", "x/oob/v1.0.x" ]
  pull_request:
    branches: [ "main", "x/oob/v1.0.x" ]
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Build library in FreeBSD VM
        id: build-lib-amd64
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: "x86_64"
          run: |
            pkg install -y multimedia/ffmpeg textproc/py-docutils multimedia/ffnvcodec-headers multimedia/v4l_compat graphics/vulkan-headers graphics/wayland-protocols devel/evdev-proto devel/desktop-file-utils devel/meson devel/ninja devel/pkgconf lang/python312 python3 x11/xorgproto x11/libX11 x11/libXext x11/libXfixes x11/libXinerama x11/libXpresent x11/libXrandr x11/libXScrnSaver x11/libXv x11/libXxf86vm converters/libiconv
            cd assets/mpv ; export CFLAGS="-DLIBICONV_PLUG" ; export CPPFLAGS="-DLIBICONV_PLUG" ; meson setup build --prefix=$(pwd)/outlib ; meson compile -C build ; meson install -C build
      - name: Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "MPV library"
          path: assets/mpv/outlib
