name: Build MPV library (Linux - ARM64)

on:
  push:
    branches: [ "main", "x/oob/v1.0.x" ]
  pull_request:
    branches: [ "main", "x/oob/v1.0.x" ]
    
jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setting up environment
        run: |
          sudo apt update
          sudo apt install build-essential meson pkg-config libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libass-dev zlib1g-dev libjpeg-dev libgl-dev libx11-dev libxrandr-dev libxext-dev libxss-dev libxpresent-dev libvdpau-dev
      - name: MPV compilation
        run: |
          cd assets/mpv ; mkdir -p subprojects ; git clone https://code.videolan.org/videolan/libplacebo.git --depth=1 --recursive subprojects/libplacebo ; meson setup build --prefix=$(pwd)/outlib ; meson compile -C build ; meson install -C build
      - name: Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "MPV library"
          path: assets/mpv/outlib
